name: none
favicon: null
layout_spectrum: 0.38148259837180376
typography_spectrum: 0.6439878179226071
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5882267772685736
  lightness: 0.8390665119513869
  saturation: 0.4088344471529126
  rhythmicContrast: 0.76143783563748
purpose: []
